const ProjectList = [
    {
      projectName: "News Buzz",
      icon: "../assets/projects/newsBuzzIco.ico",
      description: "I created News Buzz as an assignment for Persist Ventures. This web application is designed to keep users updated with the latest news. It fetches news articles from various sources and displays them in an organized manner. Key features include real-time news updates, categorization for easy navigation, and a clean, user-friendly interface for browsing news.",
      info: "React, Api's, Router, Redux, Pagination, Search Algorithm", 
      gitLink: "https://github.com/Atharv-28/news-buzz",
      snapshots: ["../assets/projects/nz1.png"], 
      liveLink: "https://news-buzz-seven.vercel.app/", 
    },
    {
      projectName: "MCQ App",
      icon: "../assets/projects/mcqIco.ico", 
      description: "I developed the MCQ App as an assessment project for TheGoodGameTheory. This web application allows users to practice multiple-choice questions, providing a platform for learning and self-assessment. It was built using React and offers a user-friendly interface for an engaging experience.",
      info: "React, Pagination, States",
      gitLink: "https://github.com/Atharv-28/mcq-app",
      snapshots: ["../assets/projects/mcq1.png"],
      liveLink: "https://mcq-app-git-main-atharv-28s-projects.vercel.app/",
    },
    {
      projectName: "To-Do List",
      icon: "../assets/projects/toDoIco.png",
      description: "I created the To-Do List app to help users manage their tasks efficiently. This application allows users to add, edit, and delete tasks, ensuring they stay organized. Built with React, it features a clean and intuitive interface for easy task management.",
      info: "HTML, CSS, JavaScript, Express.JS, MongoDB",
      gitLink: "https://github.com/Atharv-28/To-Do-List",
      snapshots: ["../assets/projects/todo1.png"],
      liveLink: "NA",
    },
    {
      projectName: "Water Level",
      icon: "../assets/projects/waterLevelIco.png",
      description: "I developed the Water Level project to monitor the water level in my house's tank. This IoT solution uses sensors and a mobile app, with Firebase as the database, to detect and display water levels. It helps in managing water resources efficiently.",
      info: "Iot, c++, Arduino, Firebase, React-Native",
      gitLink: "https://github.com/Atharv-28/WaterLevel",
      snapshots: [],
      liveLink: "APK available on GitHub",
    },
    {
      projectName: "Yog-fit",
      icon: "../assets/projects/yogFitIco.png",
      description: "Yog-fit is my final year capstone project. This application promotes fitness and wellness through yoga. It provides users with yoga routines, tracking their progress and offering personalized recommendations. Built with React Native, it aims to make yoga accessible and enjoyable.",
      info: "React-Native, Firebase",
      gitLink: "https://github.com/Atharv-28/Yog-fit",
      snapshots: ["../assets/projects/yf1.jpg","../assets/projects/yf2.jpg"],
      liveLink: "Genrate APK from GitHub",
    },
    {
      projectName: "FocusTime",
      icon: "../assets/projects/FocusTimeIco.png",
      description: "I developed FocusTime to help users manage their time effectively. This productivity app features a timer for focused work sessions and breaks, following the Pomodoro technique. It aims to boost productivity and maintain a healthy work-life balance.",
      info: "React-Native",
      gitLink: "https://github.com/Atharv-28/FocusTime",
      snapshots: [],
      liveLink: "Genrate APK from GitHub",
    },
    {
      projectName: "Gadget Zone",
      icon: "../assets/projects/gadgetZoneIco.png",
      description: "Gadget Zone is an e-commerce platform for tech enthusiasts. It showcases various gadgets and allows users to browse and purchase them. Built with React, it offers a sleek and modern interface for an enjoyable shopping experience.",
      info: "HTML, CSS, JavaScript",
      gitLink: "https://github.com/Atharv-28/Gadget-Zone",
      snapshots: ["../assets/projects/gz1.png","../assets/projects/gz2.png","../assets/projects/gz3.png"],
      liveLink: "https://atharv-28.github.io/Gadget-Zone/index.html",
    },
    {
      projectName: "RoboFriends",
      icon: "../assets/projects/robofriendsIco.png",
      description: "I created RoboFriends as a fun project to explore React. This application displays a list of robot friends, allowing users to search and filter through them. It was a great way to learn and implement React concepts in a playful manner.",
      info: "React, API, LiveSearch",
      gitLink: "https://github.com/Atharv-28/RoboFriends",
      snapshots: [],
      liveLink: "",
    }
  ];
  

  export default ProjectList;