const projects = [
    {
      projectName: "News Buzz",
      icon: "../assets/projects/newsBuzzIco.ico",
      description: "I created News Buzz as an assignment for Persist Ventures. This web application is designed to keep users updated with the latest news. It fetches news articles from various sources and displays them in an organized manner. Key features include real-time news updates, categorization for easy navigation, and a clean, user-friendly interface for browsing news.",
      info: "", // Additional information if needed
      gitLink: "https://github.com/Atharv-28/news-buzz",
      snapshots: [], // Array of snapshot image URLs if available
      liveLink: "", // URL if the project is hosted live
    },
    {
      projectName: "MCQ App",
      icon: "../assets/projects/mcqIco.ico", 
      description: "I developed the MCQ App as an assessment project for TheGoodGameTheory. This web application allows users to practice multiple-choice questions, providing a platform for learning and self-assessment. It was built using React and offers a user-friendly interface for an engaging experience.",
      info: "", // Additional information
      gitLink: "https://github.com/Atharv-28/mcq-app",
      snapshots: [],
      liveLink: "",
    },
    {
      projectName: "To-Do List",
      icon: "../assets/projects/toDoIco.png",
      description: "I created the To-Do List app to help users manage their tasks efficiently. This application allows users to add, edit, and delete tasks, ensuring they stay organized. Built with React, it features a clean and intuitive interface for easy task management.",
      info: "",
      gitLink: "https://github.com/Atharv-28/To-Do-List",
      snapshots: [],
      liveLink: "",
    },
    {
      projectName: "User Search",
      icon: "../assets/projects/userSearchIco.ico",
      description: "The User Search project was an assignment for GoBananas. This application enables users to search for and view details of other users. It was built using React and integrates with an API to fetch user data, providing a seamless search experience.",
      info: "",
      gitLink: "https://github.com/Atharv-28/user-search",
      snapshots: [],
      liveLink: "",
    },
    {
      projectName: "Water Level",
      icon: "../assets/projects/waterLevelIco.png",
      description: "I developed the Water Level project to monitor the water level in my house's tank. This IoT solution uses sensors and a mobile app, with Firebase as the database, to detect and display water levels. It helps in managing water resources efficiently.",
      info: "",
      gitLink: "https://github.com/Atharv-28/WaterLevel",
      snapshots: [],
      liveLink: "",
    },
    {
      projectName: "Yog-fit",
      icon: "../assets/projects/yogFitIco.png",
      description: "Yog-fit is my final year capstone project. This application promotes fitness and wellness through yoga. It provides users with yoga routines, tracking their progress and offering personalized recommendations. Built with React Native, it aims to make yoga accessible and enjoyable.",
      info: "",
      gitLink: "https://github.com/Atharv-28/Yog-fit",
      snapshots: [],
      liveLink: "",
    },
    {
      projectName: "Mind Plug",
      icon: "../assets/projects/mindPlugIco.ico",
      description: "I created Mind Plug to enhance mental well-being. This application offers various exercises and activities to improve focus and reduce stress. It features a user-friendly interface and is designed to help users maintain a healthy mind.",
      info: "",
      gitLink: "https://github.com/Atharv-28/Mind-Plug",
      snapshots: [],
      liveLink: "",
    },
    {
      projectName: "Top Speed",
      icon: "../assets/projects/topSpeedIco.png",
      description: "Top Speed is a project focused on tracking and improving running performance. It allows users to log their runs, track their speed, and set goals. Built with React Native, it provides a comprehensive platform for runners to enhance their performance.",
      info: "",
      gitLink: "https://github.com/Atharv-28/Top-Speed",
      snapshots: [],
      liveLink: "",
    },
    {
      projectName: "FocusTime",
      icon: "../assets/projects/FocusTimeIco.png",
      description: "I developed FocusTime to help users manage their time effectively. This productivity app features a timer for focused work sessions and breaks, following the Pomodoro technique. It aims to boost productivity and maintain a healthy work-life balance.",
      info: "",
      gitLink: "https://github.com/Atharv-28/FocusTime",
      snapshots: [],
      liveLink: "",
    },
    {
      projectName: "Gadget Zone",
      icon: "../assets/projects/gadgetZoneIco.png",
      description: "Gadget Zone is an e-commerce platform for tech enthusiasts. It showcases various gadgets and allows users to browse and purchase them. Built with React, it offers a sleek and modern interface for an enjoyable shopping experience.",
      info: "",
      gitLink: "https://github.com/Atharv-28/Gadget-Zone",
      snapshots: [],
      liveLink: "",
    },
    {
      projectName: "RoboFriends",
      icon: "../assets/projects/robofriendsIco.ico",
      description: "I created RoboFriends as a fun project to explore React. This application displays a list of robot friends, allowing users to search and filter through them. It was a great way to learn and implement React concepts in a playful manner.",
      info: "",
      gitLink: "https://github.com/Atharv-28/RoboFriends",
      snapshots: [],
      liveLink: "",
    }
  ];
  